function init(self)
	msg.post("#", "inventory_disable")
end

function final(self)
	
end

function update(self, dt)
	
end

function on_message(self, message_id, message, sender)
	if message_id == hash("inventory_enable") then
		self.active = true
		msg.post("#", "enable")
	elseif message_id == hash("inventory_disable") then
		self.active = false
		msg.post("#", "disable")
	end
end

function on_input(self, action_id, action)
	
end

function on_reload(self)
	
end
